INSERT INTO public.regulation_articles (id,chapter_id,code,title,content,content_type,sort_order) VALUES ('chuong-i-dieu-2','qcdgxl-chuong-i','chuong-i-dieu-2','Điều 2. Mục đích','1. Tiêu chí đánh giá, xếp loại hàng tháng của viên chức, người lao động Ban QLDA là căn cứ để bình xét khen thưởng, chi trả thu nhập tăng thêm hàng năm; là căn cứ để đánh giá, xếp loại thi đua; đồng thời là cơ sở để bố trí, sử dụng, quy hoạch, đề bạt, đào tạo, bồi dưỡng và thực hiện chính sách đối với cán bộ, viên chức, người lao động theo quy định và theo yêu cầu nhiệm vụ của cơ quan.

2. Đánh giá xếp loại hàng tháng đối với cán bộ, viên chức, người lao động nhằm phát huy vai trò, trách nhiệm của người đứng đầu trong công tác lãnh đạo, quản lý, siết chặt kỷ luật, kỷ cương, chuẩn hóa, xây dựng phong cách làm việc chuyên nghiệp; nâng cao ý thức trách nhiệm, tính tự giác trong thực thi công vụ của cán bộ, viên chức, người lao động; tạo môi trường sáng tạo, đổi mới, phát triển, nâng cao chất lượng, hiệu quả hoạt động của cơ quan.','text',2),('chuong-i-dieu-3','qcdgxl-chuong-i','chuong-i-dieu-3','Điều 3. Yêu cầu','1. Căn cứ vào Kế hoạch khung hàng năm của Ban QLDA, nhiệm vụ chuyên môn của các phòng và khối lượng công việc tồn đọng, các phòng thuộc Ban QLDA phải xây dựng kế hoạch công tác tháng, quý, năm; phân công cụ thể (cán bộ trực tiếp phụ trách, lãnh đạo phòng trực tiếp quản lý, lãnh đạo Ban phụ trách); nội dung công việc được giao; tiến độ, thời gian thực hiện, hoàn thành; xác định kết quả đầu ra của mỗi nhiệm vụ được giao. Trên cơ sở kế hoạch công tác của phòng, cá nhân xây dựng kế hoạch thực hiện tháng, quý, năm.

2. Việc đánh giá, xếp loại hàng tháng đối với cán bộ, viên chức, lao động phải thực hiện theo nguyên tắc tập trung dân chủ, chính xác, khách quan, công bằng, đúng thực chất và đúng trình tự quy định. Phải thực hiện đánh giá đa chiều, liên tục, lượng hóa được kết quả thực hiện nhiệm vụ của từng cán bộ, viên chức, người lao động gắn với kết quả công tác của từng bộ phận, từng phòng chuyên môn (trên cơ sở phân tích về tổng khối lượng và tính chất, mức độ của công việc).','text',3),('chuong-i-dieu-4','qcdgxl-chuong-i','chuong-i-dieu-4','Điều 4. Nguyên tắc đánh giá, xếp loại chất lượng','1. Trưởng các phòng trực tiếp lãnh đạo, giao nhiệm vụ, đồng thời là người thực hiện nhận xét, đánh giá, xếp loại viên chức và người lao động thuộc đơn vị mình. Giám đốc Ban QLDA là người đứng đầu cơ quan quyết định việc xếp loại, đánh giá cán bộ, viên chức, người lao động theo phân cấp quản lý và chịu trách nhiệm về quyết định của mình.

2. Việc đánh giá, xếp loại phải căn cứ vào chức trách, nhiệm vụ được giao và kết quả thực hiện nhiệm vụ. Việc đánh giá cần làm rõ ưu điểm, khuyết điểm, tồn tại, hạn chế về phẩm chất, năng lực, trình độ của cán bộ, viên chức, người lao động.

3. Bảo đảm dân chủ, khách quan, chính xác, công khai, minh bạch, xuyên suốt, liên tục, đa chiều.

4. Việc đánh giá, xếp loại viên chức lãnh đạo, quản lý phải dựa vào kết quả hoạt động của cơ quan, đơn vị được giao quản lý, phục trách. Mức độ hoàn thành nhiệm vụ của người đứng đầu không được cao hơn mức độ hoàn thành nhiệm vụ của đơn vị được giao quản lý, phụ trách.

5. Trường hợp cán bộ, viên chức, lao động không hoàn thành nhiệm vụ do yếu tố khách quan, bất khả kháng thì được xem xét trong quá trình đánh giá, xếp loại.','text',4) ON CONFLICT (id) DO UPDATE SET content=EXCLUDED.content,title=EXCLUDED.title;