-- Add missing compliance and approval columns to projects table
ALTER TABLE projects
ADD COLUMN IF NOT EXISTS planning_approval_number TEXT,
ADD COLUMN IF NOT EXISTS planning_approval_date DATE,
ADD COLUMN IF NOT EXISTS pccc_approval_number TEXT,
ADD COLUMN IF NOT EXISTS pccc_approval_date DATE,
ADD COLUMN IF NOT EXISTS pccc_approval_agency TEXT,
ADD COLUMN IF NOT EXISTS env_approval_number TEXT,
ADD COLUMN IF NOT EXISTS env_approval_date DATE,
ADD COLUMN IF NOT EXISTS env_approval_type TEXT,
ADD COLUMN IF NOT EXISTS appraisal_result_number TEXT,
ADD COLUMN IF NOT EXISTS appraisal_result_date DATE,
ADD COLUMN IF NOT EXISTS appraisal_agency TEXT,
ADD COLUMN IF NOT EXISTS cost_breakdown JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS design_appraisal_number TEXT,
ADD COLUMN IF NOT EXISTS design_appraisal_date DATE,
ADD COLUMN IF NOT EXISTS design_approval_number TEXT,
ADD COLUMN IF NOT EXISTS design_approval_date DATE,
ADD COLUMN IF NOT EXISTS design_approval_authority TEXT,
ADD COLUMN IF NOT EXISTS construction_permit_number TEXT,
ADD COLUMN IF NOT EXISTS construction_permit_date DATE,
ADD COLUMN IF NOT EXISTS construction_permit_agency TEXT,
ADD COLUMN IF NOT EXISTS actual_start_date_construction DATE,
ADD COLUMN IF NOT EXISTS insurance_contract TEXT,
ADD COLUMN IF NOT EXISTS insurance_value NUMERIC,
ADD COLUMN IF NOT EXISTS acceptance_result TEXT,
ADD COLUMN IF NOT EXISTS acceptance_date DATE,
ADD COLUMN IF NOT EXISTS handover_date DATE,
ADD COLUMN IF NOT EXISTS tt24_completion_pct NUMERIC,
ADD COLUMN IF NOT EXISTS province_code TEXT;
